
name: Push Docker Hub

on:
  push:
    branches: [ master, main ]
  schedule:
    # Every sunday at 0:00
    - cron:  '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Mainline Debian Version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./mainline/debian/Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: |
          jawg/nginx-spa:latest
          jawg/nginx-spa:1
          jawg/nginx-spa:mainline
    - name: Build and push Mainline Alpine Version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./mainline/debian/Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: |
          jawg/nginx-spa:alpine
          jawg/nginx-spa:1-alpine
          jawg/nginx-spa:mainline-alpine
    - name: Build and push Stable Debian Version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./stable/debian/Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: |
          jawg/nginx-spa:stable
    - name: Build and push Stable Alpine Version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./stable/debian/Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: |
          jawg/nginx-spa:stable-alpine